//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class GameMenu
	{
		public GameMenu ()
		{
		}
	}
}


/*
 * var isQuit=false;

function OnMouseEnter(){
//change text color
GetComponent.<Renderer>().material.color=Color.red;
}

function OnMouseExit(){
//change text color
GetComponent.<Renderer>().material.color=Color.blue;
}

function OnMouseUp(){
//is this quit
if (isQuit==true) {
//quit the game
Application.Quit();
}
else {
//load level
Application.LoadLevel("Minigame");
}
}

function Update(){
//quit game if escape key is pressed
if (Input.GetKey(KeyCode.Escape)) { Application.Quit();
}
}*/