using UnityEngine;

/*!PlayerMovement.cs
 * takes in player input from the keyboard and converts input to player character movement.
 * movement keys asre w,a,s,d and arrow keys*/


public class PlayerMovement : MonoBehaviour {
	
	public float speed = 6f;
	Animator anim;                     

	void Start () {anim = GetComponent <Animator> ();}

	
	void Update () {transform.Rotate(0,Input.GetAxis("Horizontal")*180*Time.deltaTime,0);
		ControlPlayer();}
	
	/*! ControlPlayer script reads the value of the 'Horizontal' and 'Veritcal' axes (generated by the Unity
	 * engine, and converts this to a movement vector, with movement in the y axis set to zero*/
	void ControlPlayer()
	{float h = Input.GetAxisRaw ("Horizontal");
		float v = Input.GetAxisRaw ("Vertical");
		Vector3 movement = new Vector3(0, 0.0f, v);
		transform.Translate (movement * speed * Time.deltaTime, Space.Self);
		bool walking = h != 0f || v != 0f;
		anim.SetBool ("IsWalking", walking);}
	
	
	
}
